sudo: require
language: cpp
compiler: gcc

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # Coverity Scan
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install: 
  # C++14
  - sudo apt-get install -qq g++-5

before_script: 
  - qmake

script: 
  - make
  - ./travis_qmake_gcc_cpp14_coverity


env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "GgAgW1tYkFns4UD+nECHNGZkwgHIHk9bNIS44HXjFObpm0RYE94PaXDlNekLNWgC3/gqcu5ORzXTSD9hBXbs+XrD3Xtb9fcCfjb2HyK4bAuUJTXBpRhAV9ZiaXAq7FdwES2rhsEjQpJDOo1XrHO/yZUrYBPpKyP6oU3eWvpMjoy5D7Yx9rLo9vff62nVaG7UoYF6SCSgLVXk0IrpvTST/JUz2fxe2wjUue8xucMXo4xJ7FuwiI2HxUVdr22qYbUDKKvH2Y4C4h/vYX3nlMw+UBRMVooMJDSFi6ltNE5tbLHVSPkCBqZYaLcapZ6LJtGLtwIMaTgbnNM+Eeyj7WdSe4PsX3dH3GPW2O4HMIaogHucRtNGweLvWdKfruWDEl27g/oFI/J6HdZUzOLrR7jHW2Otk9JfV/6E09oM6zw1fE8OB4KMNcb00IR7noEAX26k0gDfl35xLd+n87aCT/dL0614Z/dktOAGdjkFRvVqEjDGRkkZdS9Oy3h4au2yVBOelZ56CB+V8SDmEbKbxT+MS05SZUjwKOSZy25b0SnGI4+2Ctea57sMxclg++SEz+MHC31LFuLqGf8+7nBvwK86y8AKKzL2nrFAnoSSIjCFQOnadHdZQf9kYcGHm4oPHc4XHPoeCNPhBSeyNMzURzMZIt1Rvjqf7jgG3znC/ZmG5as="

addons:
  coverity_scan:
    project:
      name: "richelbilderbeek/travis_qmake_gcc_cpp14_coverity"
      description: "Testing out Coverity Scan"
    notification_email: richel@richelbilderbeek.nl
    build_command_prepend: "make clean; cov-configure --comptype gcc --compiler g++-5; qmake"
    build_command: "make"
    branch_pattern: coverity_scan

after_success:
  - cat /home/travis/build/richelbilderbeek/travis_qmake_gcc_cpp14_coverity/cov-int/scm_log.txt

after_failure:
  - cat /home/travis/build/richelbilderbeek/travis_qmake_gcc_cpp14_coverity/cov-int/scm_log.txt